name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version to be deployed'
        required: true
        default: '0.1.11'


env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  APP_NAME: 'zoltan-pal-epam-nye-progkor'

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl version
          docker pull ghcr.io/zoltan-pal/epam-nye-progkor:${{ github.event.inputs.version }}
          flyctl deploy --image ghcr.io/zoltan-pal/epam-nye-progkor:${{ github.event.inputs.version }} --now
          flyctl status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        
